FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /lokilite-agent ./cmd/agent

FROM alpine:3.19

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /lokilite-agent /app/lokilite-agent
COPY configs/agent-config.yaml /app/agent-config.yaml

CMD ["/app/lokilite-agent", "-config", "/app/agent-config.yaml"]
